# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "872c8d8e86952b030569d3765da71211"
name = "widget-setting"
handle = "widget-setting"
application_url = "https://bright-hometown-rats-return.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jason-app-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bright-hometown-rats-return.trycloudflare.com/auth/callback",
  "https://bright-hometown-rats-return.trycloudflare.com/auth/shopify/callback",
  "https://bright-hometown-rats-return.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
